### ISSUE TITLE
This is amazing and Thank You

### ISSUE THREAD

**Issue by Uncle-Khans-Phrontistery** [jalder89/raylib-macos-template-arm-cpp#2]
I was just sorting out what PaperDomo101 had written up and ran into a few issues with changes to c++ and VS and Mac silicon. Thank you so much for putting this together. Super helpful and easy to follow.

**Comment by jessatech** [comment]
You're very welcome! 😊

It took me 2 weeks of poking at Raylib off and on to figure this out. So I wanted to make sure it was documented for future me and others. PaperDomo101 is the real hero, I just made the template on Github to make it wasn't lost to Reddit and that there was a clear step by step guide.

Sorry for the delay, I didn't get any notification of the issues being filed on the repo. I fixed the typo and added clarity to Step 6, it's a issue with copy/pasting markdown and I don't think I can fix it.
